# Ingress settings
ingress:
  enabled: true
  domains:
    - my-domain.com

# Database settings
database:
  size: 50Gi
  password: "MY_PASSWORD"

# Settings for the ingress controller
nginx-ingress:
  enabled: true
  controller:
    publishService:
      enabled: true

# Disable webhook
webhook:
  enabled: false

# Settings for the cert-manager
cert-manager:
  enabled: true
  createCustomResource: false
  serviceAccount:
    create: false
    name: "default"
  webhook:
    enabled: false
  extraArgs:
    - --acme-http01-solver-resource-request-cpu=0
    - --acme-http01-solver-resource-request-memory=0
