# Images to use
images:
  devspace_auth: devspacecloud/auth:0.0.4
  devspace_hasura_migrations: devspacecloud/hasura:0.0.2
  devspace_hasura_init: devspacecloud/hasura-init:0.0.2
  devspace_manager: devspacecloud/manager:0.0.6
  devspace_default_backend: devspacecloud/default-backend:0.0.2
  devspace_admission_controller: devspacecloud/admission-controller:0.0.3
  devspace_ui: devspacecloud/ui:0.0.4

# Ingress settings
ingress:
  enabled: true
  domains:
    - my-domain.com

# Database settings
database:
  size: 50Gi
  password: "MY_PASSWORD"

# Settings for the ingress controller
nginx-ingress:
  controller:
    publishService:
      enabled: true

# Disable webhook
webhook:
  enabled: false

# Settings for the cert-manager
cert-manager:
  createCustomResource: false
  serviceAccount:
    create: false
    name: "default"
  webhook:
    enabled: false
  extraArgs:
    - --acme-http01-solver-resource-request-cpu=0
    - --acme-http01-solver-resource-request-memory=0
