apiVersion: v1
kind: ServiceAccount
metadata:
  name: devspace-cloud-sa
  labels:
    "app.kubernetes.io/managed-by": "Helm"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-20"
    "helm.sh/chart": "{{.Chart.Name}}-{{.Chart.Version}}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devspace-cloud-sa
  labels:
    "app.kubernetes.io/managed-by": "Helm"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    "helm.sh/chart": "{{.Chart.Name}}-{{.Chart.Version}}"
subjects:
- kind: ServiceAccount
  name: devspace-cloud-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io