apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-secret-generator"
  labels:
    "app.kubernetes.io/managed-by": "Helm"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/chart": "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        "app.kubernetes.io/managed-by": "Helm"
      annotations:
        "helm.sh/chart": "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      serviceAccountName: devspace-cloud-sa
      restartPolicy: Never
      containers:
      - name: create-cert-secret
        image: "roffe/kubectl:v1.13.2"
        command:
        - bash
        args:
        - "-c"
        - |
            apk update
            apk add openssl
            openssl genrsa -out key.pem 2048
            openssl req -x509 -new -key key.pem -out cert.pem -subj '/CN=localhost'
            kubectl create secret generic devspace-auth-secret \
              --from-file=key.pem \
              --from-file=cert.pem \
              --dry-run -o yaml | kubectl -n devspace-cloud apply -f -
