{{- $certManager := index .Values "cert-manager" -}}
{{- if $certManager.enabled -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: devspace-cert
spec:
  secretName: ingress-tls-secret
  dnsNames:
  {{- range $index, $domain := .Values.ingress.domains }}
    - "{{ $domain }}"
  {{- end }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      {{- range $index, $domain := .Values.ingress.domains }}
        - "{{ $domain }}"
      {{- end }}
  issuerRef:
    name: lets-encrypt-http-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
{{- end -}}
