apiVersion: v1
kind: Service
metadata:
  labels:
    app: devspace-hasura
  name: devspace-hasura
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: devspace-hasura